### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by YashasSingh** [anujdutt9/Disease-Prediction-from-Symptoms#12]
Hey whenever I install yaml it keeps on saying 
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml

Any fix for this?

**Comment by JacquelynnChapleV2** [comment]
are u finished your question?

**Comment by anujdutt9** [comment]
Hi, can you please try installing yaml using this:
```
pip install pyyaml
```
Let me know if you still have issues.
