### ISSUE TITLE
Selection of Symptoms

### ISSUE THREAD

**Issue by SaraKhatoon** [anujdutt9/Disease-Prediction-from-Symptoms#5]
How do I select the symptoms from the list ? In README.md file is it mentioned that the symptoms can be selected from a given list. Where is the list !! Also, how does the raw_data.xlsx file get created once the symptoms are selected.

Address the issue at the earliest

Regards,

**Comment by anujdutt9** [comment]
Hi. Did you try to read the Jupyter notebook ? If yes, then the first line of the notebook gives the link to the dataset.

**Comment by SaraKhatoon** [comment]
How and where is the raw_data.xlsx file generated... You've mentioned in the README.md file that symptoms should be selected from the given list... I just want to know how is raw_data.xlsx generated and from where do I select the symptoms ? Like how do I give the input

**Comment by anujdutt9** [comment]
Hi. So, if you see this link: https://impact.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html
This has a table that you can copy into an excel file. This table has 3 columns: `Disease, Count of Disease Occurrence and Symptom`
This is where the `Disease to Symptom mapping` comes from. Let me know if you still have any questions.
