### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by maneprajakta** [anujdutt9/Disease-Prediction-from-Symptoms#8]
Hi 
The dataset link provided in readme.md is different from the dataset which is present in the dataset folder the folder contains kaggle dataset.

**Comment by anujdutt9** [comment]
Hi. I have refactored the repository and cleaned up the Readme as well. Hopefully, it should be more clear now. If you still have any issues, let me know.

**Comment by maneprajakta** [comment]
Thanks @anujdutt9 it's clear now in which part these two dataset's are used :+1:.

**Comment by anujdutt9** [comment]
Awesome. Closing this issue then.
